gdjs.MenuCode = {};
gdjs.MenuCode.GDGreenButtonObjects1= [];
gdjs.MenuCode.GDGreenButtonObjects2= [];
gdjs.MenuCode.GDNewTextObjects1= [];
gdjs.MenuCode.GDNewTextObjects2= [];
gdjs.MenuCode.GDGreyButtonObjects1= [];
gdjs.MenuCode.GDGreyButtonObjects2= [];
gdjs.MenuCode.GDBlueButtonObjects1= [];
gdjs.MenuCode.GDBlueButtonObjects2= [];
gdjs.MenuCode.GDSummerTileTopLeftCornerObjects1= [];
gdjs.MenuCode.GDSummerTileTopLeftCornerObjects2= [];
gdjs.MenuCode.GDDinoObjects1= [];
gdjs.MenuCode.GDDinoObjects2= [];
gdjs.MenuCode.GDHighSpikesObjects1= [];
gdjs.MenuCode.GDHighSpikesObjects2= [];
gdjs.MenuCode.GDDeadBushObjects1= [];
gdjs.MenuCode.GDDeadBushObjects2= [];
gdjs.MenuCode.GDSummerTileTopRightCornerObjects1= [];
gdjs.MenuCode.GDSummerTileTopRightCornerObjects2= [];
gdjs.MenuCode.GDSummerTilePlatformLeftObjects1= [];
gdjs.MenuCode.GDSummerTilePlatformLeftObjects2= [];
gdjs.MenuCode.GDSummerTilePlatformRightObjects1= [];
gdjs.MenuCode.GDSummerTilePlatformRightObjects2= [];
gdjs.MenuCode.GDCloud7Objects1= [];
gdjs.MenuCode.GDCloud7Objects2= [];
gdjs.MenuCode.GDCloud3Objects1= [];
gdjs.MenuCode.GDCloud3Objects2= [];
gdjs.MenuCode.GDPlacaObjects1= [];
gdjs.MenuCode.GDPlacaObjects2= [];
gdjs.MenuCode.GDO2Objects1= [];
gdjs.MenuCode.GDO2Objects2= [];
gdjs.MenuCode.GDA2Objects1= [];
gdjs.MenuCode.GDA2Objects2= [];
gdjs.MenuCode.GDL2Objects1= [];
gdjs.MenuCode.GDL2Objects2= [];
gdjs.MenuCode.GDE2Objects1= [];
gdjs.MenuCode.GDE2Objects2= [];
gdjs.MenuCode.GDS2Objects1= [];
gdjs.MenuCode.GDS2Objects2= [];
gdjs.MenuCode.GDC2Objects1= [];
gdjs.MenuCode.GDC2Objects2= [];
gdjs.MenuCode.GDSchoolBusObjects1= [];
gdjs.MenuCode.GDSchoolBusObjects2= [];
gdjs.MenuCode.GDBookRedObjects1= [];
gdjs.MenuCode.GDBookRedObjects2= [];
gdjs.MenuCode.GDBookGreenObjects1= [];
gdjs.MenuCode.GDBookGreenObjects2= [];
gdjs.MenuCode.GDOpenBookObjects1= [];
gdjs.MenuCode.GDOpenBookObjects2= [];
gdjs.MenuCode.GDU2Objects1= [];
gdjs.MenuCode.GDU2Objects2= [];
gdjs.MenuCode.GDPlataformaObjects1= [];
gdjs.MenuCode.GDPlataformaObjects2= [];
gdjs.MenuCode.GDAtravessavelObjects1= [];
gdjs.MenuCode.GDAtravessavelObjects2= [];
gdjs.MenuCode.GDOObjects1= [];
gdjs.MenuCode.GDOObjects2= [];
gdjs.MenuCode.GDLObjects1= [];
gdjs.MenuCode.GDLObjects2= [];
gdjs.MenuCode.GDCObjects1= [];
gdjs.MenuCode.GDCObjects2= [];
gdjs.MenuCode.GDSObjects1= [];
gdjs.MenuCode.GDSObjects2= [];
gdjs.MenuCode.GDEObjects1= [];
gdjs.MenuCode.GDEObjects2= [];
gdjs.MenuCode.GDAObjects1= [];
gdjs.MenuCode.GDAObjects2= [];
gdjs.MenuCode.GDUObjects1= [];
gdjs.MenuCode.GDUObjects2= [];
gdjs.MenuCode.GDRObjects1= [];
gdjs.MenuCode.GDRObjects2= [];
gdjs.MenuCode.GDFObjects1= [];
gdjs.MenuCode.GDFObjects2= [];
gdjs.MenuCode.GDPObjects1= [];
gdjs.MenuCode.GDPObjects2= [];
gdjs.MenuCode.GDS4Objects1= [];
gdjs.MenuCode.GDS4Objects2= [];
gdjs.MenuCode.GDO3Objects1= [];
gdjs.MenuCode.GDO3Objects2= [];
gdjs.MenuCode.GDR2Objects1= [];
gdjs.MenuCode.GDR2Objects2= [];
gdjs.MenuCode.GDP2Objects1= [];
gdjs.MenuCode.GDP2Objects2= [];
gdjs.MenuCode.GDR4Objects1= [];
gdjs.MenuCode.GDR4Objects2= [];
gdjs.MenuCode.GDF2Objects1= [];
gdjs.MenuCode.GDF2Objects2= [];
gdjs.MenuCode.GDRightArrowObjects1= [];
gdjs.MenuCode.GDRightArrowObjects2= [];
gdjs.MenuCode.GDCrateObjects1= [];
gdjs.MenuCode.GDCrateObjects2= [];
gdjs.MenuCode.GDStoneBlockObjects1= [];
gdjs.MenuCode.GDStoneBlockObjects2= [];
gdjs.MenuCode.GDS5Objects1= [];
gdjs.MenuCode.GDS5Objects2= [];
gdjs.MenuCode.GDE3Objects1= [];
gdjs.MenuCode.GDE3Objects2= [];
gdjs.MenuCode.GDNObjects1= [];
gdjs.MenuCode.GDNObjects2= [];
gdjs.MenuCode.GDN2Objects1= [];
gdjs.MenuCode.GDN2Objects2= [];
gdjs.MenuCode.GDTransitionObjects1= [];
gdjs.MenuCode.GDTransitionObjects2= [];
gdjs.MenuCode.GDSmallStarObjects1= [];
gdjs.MenuCode.GDSmallStarObjects2= [];
gdjs.MenuCode.GDA3Objects1= [];
gdjs.MenuCode.GDA3Objects2= [];
gdjs.MenuCode.GDWinterBackgroundObjects1= [];
gdjs.MenuCode.GDWinterBackgroundObjects2= [];
gdjs.MenuCode.GDSummerTileWaterWavesObjects1= [];
gdjs.MenuCode.GDSummerTileWaterWavesObjects2= [];
gdjs.MenuCode.GDIceBoxObjects1= [];
gdjs.MenuCode.GDIceBoxObjects2= [];
gdjs.MenuCode.GDIglooObjects1= [];
gdjs.MenuCode.GDIglooObjects2= [];
gdjs.MenuCode.GDDPadLeftObjects1= [];
gdjs.MenuCode.GDDPadLeftObjects2= [];
gdjs.MenuCode.GDDPadRightObjects1= [];
gdjs.MenuCode.GDDPadRightObjects2= [];
gdjs.MenuCode.GDNebulaObjects1= [];
gdjs.MenuCode.GDNebulaObjects2= [];
gdjs.MenuCode.GDCrystalObjects1= [];
gdjs.MenuCode.GDCrystalObjects2= [];
gdjs.MenuCode.GDIObjects1= [];
gdjs.MenuCode.GDIObjects2= [];
gdjs.MenuCode.GDVObjects1= [];
gdjs.MenuCode.GDVObjects2= [];
gdjs.MenuCode.GDI2Objects1= [];
gdjs.MenuCode.GDI2Objects2= [];
gdjs.MenuCode.GDV2Objects1= [];
gdjs.MenuCode.GDV2Objects2= [];
gdjs.MenuCode.GDLightCastObjects1= [];
gdjs.MenuCode.GDLightCastObjects2= [];
gdjs.MenuCode.GDTopArrowRoundButton2Objects1= [];
gdjs.MenuCode.GDTopArrowRoundButton2Objects2= [];
gdjs.MenuCode.GDJoystickObjects1= [];
gdjs.MenuCode.GDJoystickObjects2= [];
gdjs.MenuCode.GDBlueBoxObjects1= [];
gdjs.MenuCode.GDBlueBoxObjects2= [];
gdjs.MenuCode.GDGreenBoxObjects1= [];
gdjs.MenuCode.GDGreenBoxObjects2= [];
gdjs.MenuCode.GDBrownBoxObjects1= [];
gdjs.MenuCode.GDBrownBoxObjects2= [];
gdjs.MenuCode.GDIceBox2Objects1= [];
gdjs.MenuCode.GDIceBox2Objects2= [];
gdjs.MenuCode.GDDino2Objects1= [];
gdjs.MenuCode.GDDino2Objects2= [];
gdjs.MenuCode.GDD2Objects1= [];
gdjs.MenuCode.GDD2Objects2= [];
gdjs.MenuCode.GDSideRectangleStoneObjects1= [];
gdjs.MenuCode.GDSideRectangleStoneObjects2= [];
gdjs.MenuCode.GDBigSquareStoneObjects1= [];
gdjs.MenuCode.GDBigSquareStoneObjects2= [];
gdjs.MenuCode.GDV3Objects1= [];
gdjs.MenuCode.GDV3Objects2= [];
gdjs.MenuCode.GDFireObjects1= [];
gdjs.MenuCode.GDFireObjects2= [];
gdjs.MenuCode.GDE4Objects1= [];
gdjs.MenuCode.GDE4Objects2= [];
gdjs.MenuCode.GDestojoObjects1= [];
gdjs.MenuCode.GDestojoObjects2= [];
gdjs.MenuCode.GDsigaObjects1= [];
gdjs.MenuCode.GDsigaObjects2= [];
gdjs.MenuCode.GDI3Objects1= [];
gdjs.MenuCode.GDI3Objects2= [];
gdjs.MenuCode.GDSmallStar2Objects1= [];
gdjs.MenuCode.GDSmallStar2Objects2= [];
gdjs.MenuCode.GDSmallStar3Objects1= [];
gdjs.MenuCode.GDSmallStar3Objects2= [];
gdjs.MenuCode.GDSmallStar4Objects1= [];
gdjs.MenuCode.GDSmallStar4Objects2= [];
gdjs.MenuCode.GDSmallStar5Objects1= [];
gdjs.MenuCode.GDSmallStar5Objects2= [];
gdjs.MenuCode.GDSmallStar6Objects1= [];
gdjs.MenuCode.GDSmallStar6Objects2= [];
gdjs.MenuCode.GDSmallStar7Objects1= [];
gdjs.MenuCode.GDSmallStar7Objects2= [];
gdjs.MenuCode.GDSmallStar8Objects1= [];
gdjs.MenuCode.GDSmallStar8Objects2= [];
gdjs.MenuCode.GDSmallStar9Objects1= [];
gdjs.MenuCode.GDSmallStar9Objects2= [];
gdjs.MenuCode.GDDemon2Objects1= [];
gdjs.MenuCode.GDDemon2Objects2= [];
gdjs.MenuCode.GDSquidleObjects1= [];
gdjs.MenuCode.GDSquidleObjects2= [];
gdjs.MenuCode.GDGreenGrass9patchObjects1= [];
gdjs.MenuCode.GDGreenGrass9patchObjects2= [];
gdjs.MenuCode.GDNewSprite2Objects1= [];
gdjs.MenuCode.GDNewSprite2Objects2= [];
gdjs.MenuCode.GDZombieBoyObjects1= [];
gdjs.MenuCode.GDZombieBoyObjects2= [];
gdjs.MenuCode.GDDino3Objects1= [];
gdjs.MenuCode.GDDino3Objects2= [];
gdjs.MenuCode.GDDino4Objects1= [];
gdjs.MenuCode.GDDino4Objects2= [];
gdjs.MenuCode.GDYellowButtonObjects1= [];
gdjs.MenuCode.GDYellowButtonObjects2= [];
gdjs.MenuCode.GDBlueButtonWithShadowObjects1= [];
gdjs.MenuCode.GDBlueButtonWithShadowObjects2= [];
gdjs.MenuCode.GDGreenButtonWithShadowObjects1= [];
gdjs.MenuCode.GDGreenButtonWithShadowObjects2= [];
gdjs.MenuCode.GDXObjects1= [];
gdjs.MenuCode.GDXObjects2= [];


gdjs.MenuCode.eventsList0 = function(runtimeScene) {

{

gdjs.copyArray(runtimeScene.getObjects("GreenButton"), gdjs.MenuCode.GDGreenButtonObjects1);

let isConditionTrue_0 = false;
isConditionTrue_0 = false;
for (var i = 0, k = 0, l = gdjs.MenuCode.GDGreenButtonObjects1.length;i<l;++i) {
    if ( gdjs.MenuCode.GDGreenButtonObjects1[i].IsPressed((typeof eventsFunctionContext !== 'undefined' ? eventsFunctionContext : undefined)) ) {
        isConditionTrue_0 = true;
        gdjs.MenuCode.GDGreenButtonObjects1[k] = gdjs.MenuCode.GDGreenButtonObjects1[i];
        ++k;
    }
}
gdjs.MenuCode.GDGreenButtonObjects1.length = k;
if (isConditionTrue_0) {
{gdjs.evtTools.runtimeScene.replaceScene(runtimeScene, "Cena 01", false);
}}

}


{

gdjs.copyArray(runtimeScene.getObjects("YellowButton"), gdjs.MenuCode.GDYellowButtonObjects1);

let isConditionTrue_0 = false;
isConditionTrue_0 = false;
for (var i = 0, k = 0, l = gdjs.MenuCode.GDYellowButtonObjects1.length;i<l;++i) {
    if ( gdjs.MenuCode.GDYellowButtonObjects1[i].IsPressed((typeof eventsFunctionContext !== 'undefined' ? eventsFunctionContext : undefined)) ) {
        isConditionTrue_0 = true;
        gdjs.MenuCode.GDYellowButtonObjects1[k] = gdjs.MenuCode.GDYellowButtonObjects1[i];
        ++k;
    }
}
gdjs.MenuCode.GDYellowButtonObjects1.length = k;
if (isConditionTrue_0) {
{gdjs.evtTools.runtimeScene.stopGame(runtimeScene);
}}

}


};

gdjs.MenuCode.func = function(runtimeScene) {
runtimeScene.getOnceTriggers().startNewFrame();

gdjs.MenuCode.GDGreenButtonObjects1.length = 0;
gdjs.MenuCode.GDGreenButtonObjects2.length = 0;
gdjs.MenuCode.GDNewTextObjects1.length = 0;
gdjs.MenuCode.GDNewTextObjects2.length = 0;
gdjs.MenuCode.GDGreyButtonObjects1.length = 0;
gdjs.MenuCode.GDGreyButtonObjects2.length = 0;
gdjs.MenuCode.GDBlueButtonObjects1.length = 0;
gdjs.MenuCode.GDBlueButtonObjects2.length = 0;
gdjs.MenuCode.GDSummerTileTopLeftCornerObjects1.length = 0;
gdjs.MenuCode.GDSummerTileTopLeftCornerObjects2.length = 0;
gdjs.MenuCode.GDDinoObjects1.length = 0;
gdjs.MenuCode.GDDinoObjects2.length = 0;
gdjs.MenuCode.GDHighSpikesObjects1.length = 0;
gdjs.MenuCode.GDHighSpikesObjects2.length = 0;
gdjs.MenuCode.GDDeadBushObjects1.length = 0;
gdjs.MenuCode.GDDeadBushObjects2.length = 0;
gdjs.MenuCode.GDSummerTileTopRightCornerObjects1.length = 0;
gdjs.MenuCode.GDSummerTileTopRightCornerObjects2.length = 0;
gdjs.MenuCode.GDSummerTilePlatformLeftObjects1.length = 0;
gdjs.MenuCode.GDSummerTilePlatformLeftObjects2.length = 0;
gdjs.MenuCode.GDSummerTilePlatformRightObjects1.length = 0;
gdjs.MenuCode.GDSummerTilePlatformRightObjects2.length = 0;
gdjs.MenuCode.GDCloud7Objects1.length = 0;
gdjs.MenuCode.GDCloud7Objects2.length = 0;
gdjs.MenuCode.GDCloud3Objects1.length = 0;
gdjs.MenuCode.GDCloud3Objects2.length = 0;
gdjs.MenuCode.GDPlacaObjects1.length = 0;
gdjs.MenuCode.GDPlacaObjects2.length = 0;
gdjs.MenuCode.GDO2Objects1.length = 0;
gdjs.MenuCode.GDO2Objects2.length = 0;
gdjs.MenuCode.GDA2Objects1.length = 0;
gdjs.MenuCode.GDA2Objects2.length = 0;
gdjs.MenuCode.GDL2Objects1.length = 0;
gdjs.MenuCode.GDL2Objects2.length = 0;
gdjs.MenuCode.GDE2Objects1.length = 0;
gdjs.MenuCode.GDE2Objects2.length = 0;
gdjs.MenuCode.GDS2Objects1.length = 0;
gdjs.MenuCode.GDS2Objects2.length = 0;
gdjs.MenuCode.GDC2Objects1.length = 0;
gdjs.MenuCode.GDC2Objects2.length = 0;
gdjs.MenuCode.GDSchoolBusObjects1.length = 0;
gdjs.MenuCode.GDSchoolBusObjects2.length = 0;
gdjs.MenuCode.GDBookRedObjects1.length = 0;
gdjs.MenuCode.GDBookRedObjects2.length = 0;
gdjs.MenuCode.GDBookGreenObjects1.length = 0;
gdjs.MenuCode.GDBookGreenObjects2.length = 0;
gdjs.MenuCode.GDOpenBookObjects1.length = 0;
gdjs.MenuCode.GDOpenBookObjects2.length = 0;
gdjs.MenuCode.GDU2Objects1.length = 0;
gdjs.MenuCode.GDU2Objects2.length = 0;
gdjs.MenuCode.GDPlataformaObjects1.length = 0;
gdjs.MenuCode.GDPlataformaObjects2.length = 0;
gdjs.MenuCode.GDAtravessavelObjects1.length = 0;
gdjs.MenuCode.GDAtravessavelObjects2.length = 0;
gdjs.MenuCode.GDOObjects1.length = 0;
gdjs.MenuCode.GDOObjects2.length = 0;
gdjs.MenuCode.GDLObjects1.length = 0;
gdjs.MenuCode.GDLObjects2.length = 0;
gdjs.MenuCode.GDCObjects1.length = 0;
gdjs.MenuCode.GDCObjects2.length = 0;
gdjs.MenuCode.GDSObjects1.length = 0;
gdjs.MenuCode.GDSObjects2.length = 0;
gdjs.MenuCode.GDEObjects1.length = 0;
gdjs.MenuCode.GDEObjects2.length = 0;
gdjs.MenuCode.GDAObjects1.length = 0;
gdjs.MenuCode.GDAObjects2.length = 0;
gdjs.MenuCode.GDUObjects1.length = 0;
gdjs.MenuCode.GDUObjects2.length = 0;
gdjs.MenuCode.GDRObjects1.length = 0;
gdjs.MenuCode.GDRObjects2.length = 0;
gdjs.MenuCode.GDFObjects1.length = 0;
gdjs.MenuCode.GDFObjects2.length = 0;
gdjs.MenuCode.GDPObjects1.length = 0;
gdjs.MenuCode.GDPObjects2.length = 0;
gdjs.MenuCode.GDS4Objects1.length = 0;
gdjs.MenuCode.GDS4Objects2.length = 0;
gdjs.MenuCode.GDO3Objects1.length = 0;
gdjs.MenuCode.GDO3Objects2.length = 0;
gdjs.MenuCode.GDR2Objects1.length = 0;
gdjs.MenuCode.GDR2Objects2.length = 0;
gdjs.MenuCode.GDP2Objects1.length = 0;
gdjs.MenuCode.GDP2Objects2.length = 0;
gdjs.MenuCode.GDR4Objects1.length = 0;
gdjs.MenuCode.GDR4Objects2.length = 0;
gdjs.MenuCode.GDF2Objects1.length = 0;
gdjs.MenuCode.GDF2Objects2.length = 0;
gdjs.MenuCode.GDRightArrowObjects1.length = 0;
gdjs.MenuCode.GDRightArrowObjects2.length = 0;
gdjs.MenuCode.GDCrateObjects1.length = 0;
gdjs.MenuCode.GDCrateObjects2.length = 0;
gdjs.MenuCode.GDStoneBlockObjects1.length = 0;
gdjs.MenuCode.GDStoneBlockObjects2.length = 0;
gdjs.MenuCode.GDS5Objects1.length = 0;
gdjs.MenuCode.GDS5Objects2.length = 0;
gdjs.MenuCode.GDE3Objects1.length = 0;
gdjs.MenuCode.GDE3Objects2.length = 0;
gdjs.MenuCode.GDNObjects1.length = 0;
gdjs.MenuCode.GDNObjects2.length = 0;
gdjs.MenuCode.GDN2Objects1.length = 0;
gdjs.MenuCode.GDN2Objects2.length = 0;
gdjs.MenuCode.GDTransitionObjects1.length = 0;
gdjs.MenuCode.GDTransitionObjects2.length = 0;
gdjs.MenuCode.GDSmallStarObjects1.length = 0;
gdjs.MenuCode.GDSmallStarObjects2.length = 0;
gdjs.MenuCode.GDA3Objects1.length = 0;
gdjs.MenuCode.GDA3Objects2.length = 0;
gdjs.MenuCode.GDWinterBackgroundObjects1.length = 0;
gdjs.MenuCode.GDWinterBackgroundObjects2.length = 0;
gdjs.MenuCode.GDSummerTileWaterWavesObjects1.length = 0;
gdjs.MenuCode.GDSummerTileWaterWavesObjects2.length = 0;
gdjs.MenuCode.GDIceBoxObjects1.length = 0;
gdjs.MenuCode.GDIceBoxObjects2.length = 0;
gdjs.MenuCode.GDIglooObjects1.length = 0;
gdjs.MenuCode.GDIglooObjects2.length = 0;
gdjs.MenuCode.GDDPadLeftObjects1.length = 0;
gdjs.MenuCode.GDDPadLeftObjects2.length = 0;
gdjs.MenuCode.GDDPadRightObjects1.length = 0;
gdjs.MenuCode.GDDPadRightObjects2.length = 0;
gdjs.MenuCode.GDNebulaObjects1.length = 0;
gdjs.MenuCode.GDNebulaObjects2.length = 0;
gdjs.MenuCode.GDCrystalObjects1.length = 0;
gdjs.MenuCode.GDCrystalObjects2.length = 0;
gdjs.MenuCode.GDIObjects1.length = 0;
gdjs.MenuCode.GDIObjects2.length = 0;
gdjs.MenuCode.GDVObjects1.length = 0;
gdjs.MenuCode.GDVObjects2.length = 0;
gdjs.MenuCode.GDI2Objects1.length = 0;
gdjs.MenuCode.GDI2Objects2.length = 0;
gdjs.MenuCode.GDV2Objects1.length = 0;
gdjs.MenuCode.GDV2Objects2.length = 0;
gdjs.MenuCode.GDLightCastObjects1.length = 0;
gdjs.MenuCode.GDLightCastObjects2.length = 0;
gdjs.MenuCode.GDTopArrowRoundButton2Objects1.length = 0;
gdjs.MenuCode.GDTopArrowRoundButton2Objects2.length = 0;
gdjs.MenuCode.GDJoystickObjects1.length = 0;
gdjs.MenuCode.GDJoystickObjects2.length = 0;
gdjs.MenuCode.GDBlueBoxObjects1.length = 0;
gdjs.MenuCode.GDBlueBoxObjects2.length = 0;
gdjs.MenuCode.GDGreenBoxObjects1.length = 0;
gdjs.MenuCode.GDGreenBoxObjects2.length = 0;
gdjs.MenuCode.GDBrownBoxObjects1.length = 0;
gdjs.MenuCode.GDBrownBoxObjects2.length = 0;
gdjs.MenuCode.GDIceBox2Objects1.length = 0;
gdjs.MenuCode.GDIceBox2Objects2.length = 0;
gdjs.MenuCode.GDDino2Objects1.length = 0;
gdjs.MenuCode.GDDino2Objects2.length = 0;
gdjs.MenuCode.GDD2Objects1.length = 0;
gdjs.MenuCode.GDD2Objects2.length = 0;
gdjs.MenuCode.GDSideRectangleStoneObjects1.length = 0;
gdjs.MenuCode.GDSideRectangleStoneObjects2.length = 0;
gdjs.MenuCode.GDBigSquareStoneObjects1.length = 0;
gdjs.MenuCode.GDBigSquareStoneObjects2.length = 0;
gdjs.MenuCode.GDV3Objects1.length = 0;
gdjs.MenuCode.GDV3Objects2.length = 0;
gdjs.MenuCode.GDFireObjects1.length = 0;
gdjs.MenuCode.GDFireObjects2.length = 0;
gdjs.MenuCode.GDE4Objects1.length = 0;
gdjs.MenuCode.GDE4Objects2.length = 0;
gdjs.MenuCode.GDestojoObjects1.length = 0;
gdjs.MenuCode.GDestojoObjects2.length = 0;
gdjs.MenuCode.GDsigaObjects1.length = 0;
gdjs.MenuCode.GDsigaObjects2.length = 0;
gdjs.MenuCode.GDI3Objects1.length = 0;
gdjs.MenuCode.GDI3Objects2.length = 0;
gdjs.MenuCode.GDSmallStar2Objects1.length = 0;
gdjs.MenuCode.GDSmallStar2Objects2.length = 0;
gdjs.MenuCode.GDSmallStar3Objects1.length = 0;
gdjs.MenuCode.GDSmallStar3Objects2.length = 0;
gdjs.MenuCode.GDSmallStar4Objects1.length = 0;
gdjs.MenuCode.GDSmallStar4Objects2.length = 0;
gdjs.MenuCode.GDSmallStar5Objects1.length = 0;
gdjs.MenuCode.GDSmallStar5Objects2.length = 0;
gdjs.MenuCode.GDSmallStar6Objects1.length = 0;
gdjs.MenuCode.GDSmallStar6Objects2.length = 0;
gdjs.MenuCode.GDSmallStar7Objects1.length = 0;
gdjs.MenuCode.GDSmallStar7Objects2.length = 0;
gdjs.MenuCode.GDSmallStar8Objects1.length = 0;
gdjs.MenuCode.GDSmallStar8Objects2.length = 0;
gdjs.MenuCode.GDSmallStar9Objects1.length = 0;
gdjs.MenuCode.GDSmallStar9Objects2.length = 0;
gdjs.MenuCode.GDDemon2Objects1.length = 0;
gdjs.MenuCode.GDDemon2Objects2.length = 0;
gdjs.MenuCode.GDSquidleObjects1.length = 0;
gdjs.MenuCode.GDSquidleObjects2.length = 0;
gdjs.MenuCode.GDGreenGrass9patchObjects1.length = 0;
gdjs.MenuCode.GDGreenGrass9patchObjects2.length = 0;
gdjs.MenuCode.GDNewSprite2Objects1.length = 0;
gdjs.MenuCode.GDNewSprite2Objects2.length = 0;
gdjs.MenuCode.GDZombieBoyObjects1.length = 0;
gdjs.MenuCode.GDZombieBoyObjects2.length = 0;
gdjs.MenuCode.GDDino3Objects1.length = 0;
gdjs.MenuCode.GDDino3Objects2.length = 0;
gdjs.MenuCode.GDDino4Objects1.length = 0;
gdjs.MenuCode.GDDino4Objects2.length = 0;
gdjs.MenuCode.GDYellowButtonObjects1.length = 0;
gdjs.MenuCode.GDYellowButtonObjects2.length = 0;
gdjs.MenuCode.GDBlueButtonWithShadowObjects1.length = 0;
gdjs.MenuCode.GDBlueButtonWithShadowObjects2.length = 0;
gdjs.MenuCode.GDGreenButtonWithShadowObjects1.length = 0;
gdjs.MenuCode.GDGreenButtonWithShadowObjects2.length = 0;
gdjs.MenuCode.GDXObjects1.length = 0;
gdjs.MenuCode.GDXObjects2.length = 0;

gdjs.MenuCode.eventsList0(runtimeScene);

return;

}

gdjs['MenuCode'] = gdjs.MenuCode;
